Updated dc to handle setting permissions

diff --git a/dc b/dc
--- a/dc
+++ b/dc
@@ -3,22 +3,23 @@
 # Builds configuration environment and required files accoring to the directory structure:
 # ├── config
 # │   ├── all
-# │   │   ├── copy-source
+# │   │   ├── copy-source  <--- source is copied verbatim
 # │   │   │   └── etc
 # │   │   │       └── nginx
 # │   │   │           ├── nginx.conf
 # │   │   ├── environment.conf
-# │   │   └── gen-source
+# │   │   └── gen-source   <--- source is subsituted with enviroment, first from Root, then from All, then from Configuration Environment
 # │   │       └── etc
 # │   │           └── nginx
 # │   │               └── sites-enabled
 # │   │                   ├── codermerlin.com.conf
+# │   │   ├── permissions.conf <--- applies ownership and permissions changes to files, relative to the $configuration/target directory
+# │   │                             Line format: <relativePathname> <ownerUser> <ownerGroup> <permssions>
+# │   │                             Example:     ./etc/nginx/nginx.conf:root:root:644
 # │   └── prd
 # │       ├── docker-compose.yml
-# │       ├── docker-compose.yml~
 # │       ├── environment.conf
-# │       ├── environment.conf~
-# │       └── target
+# │       └── target    <---- $targetEnvironmentPath for configuration 'prd'
 # │           └── etc
 # │               └── nginx
 # │                   ├── nginx.conf
@@ -38,7 +39,11 @@
 # 3. Loads .yml files
 #    a. Loads docker-compose.yml from the current directory
 #    b. Loads docker-compose.yml from the configuration directory
-# 4. Sets the --project-name to directoryName-configuration
+# 4. Docker-compose may reference the target directory
+#    with the environment variable $targetEnvironmentPath
+# 5. Sets the --project-name to directoryName-configuration
+
+
 #
 # Environment:
 # If DC_DEBUG=1 dumps environment before execution
@@ -54,6 +59,7 @@ shift
 # Set parameters
 rootEnvironmentPath=/root/docker
 globalEnvironmentPath=./config/all
+permissionsPathname=$globalEnvironmentPath/permissions.conf
 globalEnvironmentCopySourcePath=$globalEnvironmentPath/copy-source
 globalEnvironmentGenSourcePath=$globalEnvironmentPath/gen-source
 configEnvironmentPath=./config/$configuration
@@ -112,6 +118,12 @@ then
     exit 1
 fi
 
+# Validate presence of permission file
+if [ ! -f "$permissionsPathname" ]
+then
+    echo "Unable to find permissions '$permissionsPathname'"
+    exit 1
+fi
 
 # Load environment (silently)
 export $(envsubst < "$rootEnvironmentPathname" | grep -v '^#')       > /dev/null
@@ -144,6 +156,36 @@ do
     mkdir -p "$targetDir"
     envsubst < "$source" > "$target"
 done;
+
+# Apply ownership and permissions changes
+while IFS=':' read -ra line
+do
+    if [ ! ${#line[@]} -eq 4 ]
+    then
+	echo "Incorrect permssions syntax in line: $line"
+	exit 1
+    fi
+    
+    relativePathname=${line[0]}
+    ownerUser=${line[1]}
+    ownerGroup=${line[2]}
+    permissions=${line[3]}
+    
+    fullPathname="$targetEnvironmentPath/$relativePathname"
+
+    if [ ${DC_DEBUG:-0} = "1" ]
+    then
+	echo "Setting ownership of   '$fullPathname' to '$ownerUser':'$ownerGroup'"
+	echo "Setting permissions of '$fullPathname' to '$permissions'"
+    fi
+
+    chown "$ownerUser":"$ownerGroup" "$fullPathname"
+    chmod "$permissions" "$fullPathname"
+done < $permissionsPathname
+
+
+# Export the target environment path for use by docker-compose
+export targetEnvironmentPath=$targetEnvironmentPath
 
 # Executes docker-compose for a specific enviroment named CONFIGURATION
 commandLine="docker-compose -f docker-compose.yml -f $configEnvironmentPath/docker-compose.yml --project-name $projectName $@"
